name: CI

on:
  push:
  pull_request:

jobs:
  
  build-arm64:
    runs-on: ubuntu-latest
    container:
      image: clickable/ci-20.04-arm64
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build
        run: clickable build  --accept-review-warnings --accept-review-errors
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-build
          path: build/*/app/*.click
      - name: Upload artifact on release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/*/app/*.click
          asset_name: arm64-build.click
          asset_content_type: application/octet-stream

  
