name: CI

on:
  push:
  pull_request:

jobs:
  
  build-arm64:
    runs-on: ubuntu-latest
    container:
      image: clickable/ci-20.04-arm64
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build
        run: clickable build  --accept-review-warnings --accept-review-errors
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-build
          path: build/*/app/*.click


  
