name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  
  build-arm64:
    runs-on: ubuntu-latest
    env:
      ARCH: arm64
      ARCH_TRIPLET: aarch64-linux-gnu
    container:
      image: clickable/ci-20.04-arm64
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build
        run: clickable build --clean --accept-review-warnings --accept-review-errors
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-build
          path: build/*/app/*.click
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*/app/*.click
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
