name: CI

on:
  push:

jobs:
  
  build-arm64:
    runs-on: ubuntu-latest
    container:
      image: clickable/ci-20.04-arm64
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Build
        run: clickable build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-build
          path: build/*/app/*.click


  
